### PR TITLE
Fix for browserify

### PR DESCRIPTION
**Pull request by hiddentao**
Browserify can't process dynamic require() expressions so use static ones.

### CODE REVIEW

**Comment by vanng822** [comment]
Hi @hiddentao, thank you for your pull request.

Can you explain what you tried to fix? or what is your use case?
Your change is equivalent to the old code. Be aware that usage in browser need to cross browser compatible (browser.js). There is a build script for generating browser releases

**Comment by hiddentao** [comment]
@vanng822 I want to `require()` this module into front-end code that then gets bundled using Browserify. Browserify usually automatically grabs it from the `node_modules` folder, scans the `require()` calls within and includes all the necessary files. In order to do this it can't have dynamic `require()` statements as you had. 

I can see why the calls were dynamic. It saves on code repetition. But it also breaks Browserify's operation. I had a look at Browserify's docs to see if I could get it to understand the dynamic expressions but to no avail. And explicitly telling Browserify that it needed to bundle the addition files in the `lib` folder didn't feel like the right solution to me.

**Comment by vanng822** [comment]
@hiddentao I haven't used Browserify but it feels like they should support dynamic require. I can think of many packages out there doing dynamic require.

Another note here is that there is a browser.js in the lib. I separated it to make clear that part of the code should be loaded in browser but not in node-environment. It patches Object.keys and util.inherits

Wonder if Browserify support any spec file, such as browserify.js? or any spec in package.json? I haven't really done any frontend coding for the latest 5 years so I haven't spend much time on support other nice tools than the traditional way of loading code into browser.

**Comment by hiddentao** [comment]
Ok, I guess I can have a look at browser.js and see if I can make it work that way. Will let you know how it works out.

**Comment by vanng822** [comment]
With that I mean that it is ok to make require for each file but we need to require browser.js

**Comment by vanng822** [comment]
Thanks, it would be nice if we can solve this.

**Comment by vanng822** [comment]
Here it is https://github.com/substack/browserify-handbook#browser-field

{
  "name": "mypkg",
  "version": "1.2.3",
  "main": "main.js",
  "browser": "browser.js"
}

**Comment by vanng822** [comment]
would be good to call it browserify.js instead of browser.js :-)

**Comment by hiddentao** [comment]
Ok just took a look at `browser.js`. It seems that all it does is patch other functions. You'd still need to include the other files.

When I incorporate this patch browserify is automatically able to go and include all the other files, which means I don't even need to use `browser.js`. Browserify pulls in and provides browser-friendly versions of node's `util` module.

From https://github.com/substack/node-browserify/issues/377 it seems that using dynamic require expressions aren't within browserify's scope. However there is a [bulkify](https://github.com/substack/bulkify) transform for browserify which may can be used to "bulk require" glob paths. This looks for calls using [bulk-require](https://www.npmjs.com/package/bulk-require). 

So either we rewrite `index.js` to use a `require-bulk` call and then specify the use of `bulkify` in the docs or we actually build a self-contained module and save that as `browser.js` which can then be used with browserify (and make building that part of the build process).

**Comment by vanng822** [comment]
If it handles Object.keys then we can go with your changes. And you have tested them in different browsers?

I unfortunately don't have my home computer today so can not test (and also take some time to set up browserify).

**Comment by vanng822** [comment]
@hiddentao I will merge now

**Comment by vanng822** [comment]
It is now published
thank you for your PR!

**Comment by hiddentao** [comment]
Thanks for the merge. Sorry I couldn't get back to you in time, but it does work in all browsers (mostly thanks to Browserify doing the right thing).

**Pull request merged**
